# Generated by Django 4.1.3 on 2023-03-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
