# Generated by Django 4.1.3 on 2023-02-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0002_uservalidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservalidity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
