# Generated by Django 4.1.3 on 2023-03-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0007_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
