# Generated by Django 4.1.3 on 2023-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0008_remove_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], null=True),
        ),
    ]
