# Generated by Django 4.1.5 on 2023-03-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0009_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flipkart_api.product')),
            ],
        ),
    ]
