# Generated by Django 4.1.5 on 2023-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0010_wishlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlists',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
