# Generated by Django 4.1.5 on 2023-03-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0013_addon_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
