# Generated by Django 4.1.3 on 2023-03-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0015_alter_addon_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addon',
            unique_together=set(),
        ),
    ]
