# Generated by Django 4.1.3 on 2023-03-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0016_alter_addon_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addon',
            unique_together={('date', 'bio')},
        ),
    ]
