# Generated by Django 4.1.3 on 2023-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0018_category_product_seller_rating_user_delete_addon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
