# Generated by Django 4.1.3 on 2023-03-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0019_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
