# Generated by Django 4.1.3 on 2023-04-03 10:00

from django.db import migrations, models
import flipkart_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0022_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=flipkart_api.models.profile_path_handler),
        ),
    ]
