# Generated by Django 4.1.3 on 2023-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0023_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(default=987654321),
        ),
    ]
