# Generated by Django 4.1.3 on 2023-04-04 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flipkart_api', '0027_saveproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveProduct',
            new_name='SavedProduct',
        ),
    ]
