# Generated by Django 4.1.3 on 2023-04-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flipkart_api', '0028_rename_saveproduct_savedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='currentuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
