# Generated by Django 4.1.3 on 2023-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0029_remove_savedproduct_user_savedproduct_currentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
