# Generated by Django 4.1.3 on 2023-04-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_api', '0031_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='date',
        ),
    ]
