# Generated by Django 4.1.3 on 2023-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ManyToManyField(to='flipkart_app.address'),
        ),
    ]
