# Generated by Django 4.1.5 on 2023-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0004_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
    ]
