# Generated by Django 4.1.3 on 2023-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0006_remove_order_ordered_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('dispatched', 'dispatched'), ('in-transit', 'in-transit'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='order-placed', max_length=120),
        ),
    ]
