# Generated by Django 4.1.3 on 2023-03-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0008_remove_order_cart_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order-placed', 'Order-placed'), ('Dispatched', 'Dispatched'), ('In-transit', 'In-transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='order-placed', max_length=120),
        ),
    ]
