# Generated by Django 4.1.5 on 2023-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order-placed', 'Order-placed'), ('Dispatched', 'Dispatched'), ('In-transit', 'In-transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order-placed', max_length=120),
        ),
    ]
