# Generated by Django 4.1.5 on 2023-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0012_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
