# Generated by Django 4.1.3 on 2023-03-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0013_userprofile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
